### ISSUE TITLE
Per-file volume settings

### ISSUE THREAD

**Issue by aleksejrs** [kelciour/movies2anki#13]
Some files have a different volume. I couldn't get a file-specific configuration file to work.

**Comment by kelciour** [comment]
https://mpv.io/manual/master/#file-specific-configuration-files

For example, on Windows.

`%APPDATA%\mpv\mpv.conf`

> use-filedir-conf=yes

`D:\Movies\video.mp4`

`D:\Movies\video.mp4.conf`

> volume=130

https://mpv.io/manual/master/#options-volume
https://mpv.io/manual/master/#options-softvol-max

or something like

> af=loudnorm=I=-16

https://wiki.archlinux.org/index.php/mpv#Volume_normalization

**Comment by aleksejrs** [comment]
Sorry, I put the file into the `~/.config/mpv/` of the wrong user. Extra thanks for the `af=loudnorm`.
