### ISSUE TITLE
Why is the output format video instead of screenshots?

### ISSUE THREAD

**Issue by hxse** [kelciour/movies2anki#16]
How to output screenshots?

**Comment by kelciour** [comment]
Select "movies2anki - subs2srs".

![изображение](https://user-images.githubusercontent.com/16260735/117563412-5ada8300-b0ae-11eb-8451-f35826a13918.png)

**Comment by hxse** [comment]
@kelciour 
![image](https://user-images.githubusercontent.com/22582226/117572001-876cba00-b103-11eb-8d8a-48252b41bee1.png)

On windows, It have on "model" button.
The zip package I downloaded  that version is 1.6.1

**Comment by kelciour** [comment]
The standalone app is no longer being updated. To generate screenshots, install the add-on - https://ankiweb.net/shared/info/939347702

To make it work, you'll need to download mpv and ffmpeg and add both of them to the PATH environment variable and restart Anki. Maybe mpv could be skipped but I'm not sure and haven't tested it yet.
