### ISSUE TITLE
Can not export audio

### ISSUE THREAD

**Issue by hxse** [kelciour/movies2anki#17]
When i export .apkg file on win10, the .mp3 is not exported, but img is Normal export.
What's going on here?

**Comment by hxse** [comment]
[sound:] tag written into the HTLM instead of the field.
The reason may be this.

**Comment by hxse** [comment]
In html template:
Change `<div class="media">[sound:{{Audio}}]</div>`
To `<div class="media">{{Audio Sound}}</div>`
The problem solving But the question can't be repeated.
I wonder what's going on.

**Comment by hxse** [comment]
Change `[sound:{{Audio}}]` to `{{Audio}}` in html template.
Regular batch replacement `.*` to `[sound:$1]` in Audio card field.
Problem solved but I still want to solve it from the plug-in itself.

**Comment by kelciour** [comment]
The add-on doesn't generate audio by default. If you look in the collection.media folder, there will be only pictures.

https://docs.ankiweb.net/files.html#file-locations

To generate audio, Tools - Generate Mobile Cards could be used.

Some time later there probably will be an option to generate audio at the same time with pictures.

**Comment by hxse** [comment]
How do I specify the target deck for "Generate Mobile Cards Tool".
