### ISSUE TITLE
How to import youtube automatic captioning

### ISSUE THREAD

**Issue by hxse** [kelciour/movies2anki#18]
Unable to split the subtitles properly when i import youtube automatic captioning.
But Manual uploading of subtitles is normal.
Example: https://www.youtube.com/watch?v=En8Tz2RzubE
Script for downloading subtitles: https://greasyfork.org/en/scripts/5368-youtube-subtitle-downloader-v28

**Comment by kelciour** [comment]
Thank you for the issue and how to reproduce it. It should be fixed now. Use Tools > Add-ons > Check for Updates to update the add-on and restart Anki.

---

Currently, subtitles can be imported in 3 different ways.

1. **(exact mode)** Set "Get between Phrases to 0.0" and uncheck the checkbox. The add-on will generate as many cards ("phrases") as many subtitle lines in the subtitle file.

![изображение](https://user-images.githubusercontent.com/16260735/119263148-89944580-bbe6-11eb-9678-7e204781ca33.png)

2 **(sentence mode)** Set "Get between Phrases to 0.0" and check the checkbox. The add-on will try to join subtitle lines into sentences, for example, by joining two subtitles if the first one ends with ", ". The maximum duration of a sentence is set to 15 seconds, if "Split Long Phrases" option is set to 0 or not enabled.

![изображение](https://user-images.githubusercontent.com/16260735/119263323-3a024980-bbe7-11eb-903e-7865a0b0f0f4.png)

3. **(phrase mode)** Set "Get between Phrases" to 0.25, 0,75, 1,25, ... and maybe use "Split Long Phrases" too. The add-on will join subtitle lines into sentences, then into phrases and try to split phrases that were too long.

![изображение](https://user-images.githubusercontent.com/16260735/119263507-0378fe80-bbe8-11eb-9556-46a539fa6f5b.png)
