### ISSUE TITLE
ImportError: No module named PyQt4

### ISSUE THREAD

**Issue by Unders0und** [kelciour/movies2anki#21]
Getting that error when trying to install movies2anki in my Linux computer

```
Traceback (most recent call last):
  File "movies2anki.py", line 15, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4

```

Zorin OS 16 (focal)

**Comment by kelciour** [comment]
PyQt4 reached end-of-life on 2018-08-31. For PyQt5 try this version - https://gist.github.com/kelciour/248c0336da7f882e7b9b25a5af60ea83. It's from https://github.com/kelciour/movies2anki/issues/6.

But the most updated version of movies2anki is available as an Anki add-on - https://ankiweb.net/shared/info/939347702
