### ISSUE TITLE
python movies2anki.py zsh: command not found: python

### ISSUE THREAD

**Issue by tyschauster** [kelciour/movies2anki#24]
So....does this Anki plugin no longer work or what...?  I'm guessing not since I see no new reviews on YouTube or comments that are more recent than a year or two ago... I get to the end of installing all the different stuff through Terminal and I get this error code.  I can't prompt Movies2anki plugin to open.  Anybody...?

**Comment by kelciour** [comment]
The add-on works (for me) but it's limited to Anki 2.1.49 for now and I'm on Windows (but should work on macOS too).

About 'zsh: command not found: python', something like this usually could be solved by Google via StackOverflow - https://www.google.com/search?q=zsh%3A+command+not+found%3A+python
Maybe this one - https://stackoverflow.com/questions/74112233/python-command-not-working-in-mac-terminal or https://dev.to/smpnjn/how-to-fix-zsh-command-not-found-python-22j8
