### ISSUE TITLE
[feature]subtitle shift time

### ISSUE THREAD

**Issue by Sheldontao** [kelciour/movies2anki#31]
sometimes, the subtitles just have a little time lag to Videos.

<img width="631" alt="image" src="https://github.com/kelciour/movies2anki/assets/36765652/48cdea0a-4805-4052-b314-2bb258478c13">

**Comment by kelciour** [comment]
Thank you very much for suggesting this feature but I recommend using Aegisub or Subtitle Edit to adjust the timings. There're also tools like https://github.com/kaegi/alass and https://github.com/smacke/ffsubsync that might help but I don't have any experience with them.
