### ISSUE TITLE
[Enhancement] fix broken images and add explanation of movies and phrases button. 

### ISSUE THREAD

**Issue by cocowash** [kelciour/movies2anki#35]
Hi, thanks for developing the Add-on, I just wonder if you could fix the broken images from the anki add-on webpage and
also, adding the explanation in the read me about the difference between the button Movie and Phrases that you commented some time ago to a user. 

> For phrases, the add-on will only use timings from the subtitles to generate cards, i.e. everything that doesn't have subtitles will be ignored like the start of the video or scene changes where usually no one speaks and there are no subtitles.
For movie, the add-on will change the subtitles' timings to make them continuous to be able to watch the video from start to finish without missing anything, i.e. the end time of each line in the subtitles will be changed to match the start time of the next line.

I think it would be more user-friendly, specially for the newer users. thanks

**Comment by kelciour** [comment]
Thank you! I updated the description and added the explanation.

About the images, they're hosted on imgur.com, maybe there was some outage, but they look good to me now.
