### ISSUE TITLE
Support WebVTT subtitles

### ISSUE THREAD

**Issue by aleksejrs** [kelciour/movies2anki#5]
[WebVTT](https://en.wikipedia.org/wiki/WebVTT) is a subtitle file format based on SRT (so they are very similar). It is supported by Web browsers and used by YouTube.

**Comment by kelciour** [comment]
Thank you for your suggestion. I'll keep it in mind when/if the add-on will be updated to Anki 2.1.

**Comment by aleksejrs** [comment]
So they work, although there is/was a bug. I also had a file that didn't work because at least the hour was not specified.
