### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by keikoro** [kelciour/movies2anki#6]
Are there any plans to port this project to Python 3? Esp. wrt official Python 2.7 support ending next year, and many major projects dropping it by 2020 as well.

**Comment by MayankPandey01** [comment]
If we need it to reach out a large audience then it should be ported. bcoz many platforms have already switched to latest python (3.7)

**Comment by kelciour** [comment]
If this is about this repository and movies2anki standalone app, I quickly updated it to PyQt5 and Python 3 a couple of years ago. The code is [here](https://gist.github.com/kelciour/248c0336da7f882e7b9b25a5af60ea83).

If this is about movies2anki [addon](https://ankiweb.net/shared/info/939347702) for Anki 2.0, I really want to update it to Anki 2.1, but I have a couple of unfinished projects that I'd like to make first and don't see it happen anytime soon.

**Comment by MayankPandey01** [comment]
@kelciour i would also like to see that happen. hope u finish your unfinished work soon. feel free to reach out if I would be of some help :-)

**Comment by keikoro** [comment]
@kelciour I was indeed asking about this repo!

Are you planning to merge that Gist into here, i.e. to officially update the code to Python 3? If not, I think a link to the Gist from the README would make sense.

**Comment by kelciour** [comment]
@keikoro Unlikely, as it's a bit out of date, and probably this issue is visible enough, contains all relevant information about Python 3 version of the script and I don't want to repeat it in the README. The main options are all there, but the script doesn't contain additional options to export video clips with subtitles (softsub or hardsub).

**Comment by keikoro** [comment]
@kelciour Thanks for the info. Can your project be reused and modified? I didn't see a license file or licence-related info (would you mind adding one if it's meant to be open source?).

**Comment by kelciour** [comment]
Sure. It should be AGPL3. I'll update repository and add information about its license some time later.

It was my first relatively big Python and PyQt open source project and I didn't know what license should I use, but as movies2anki add-on reuses all the code and it's been published on AnkiWeb, its code should be licensed under the AGPL3 or a compatible license according to [AnkiWeb Account Terms](https://ankiweb.net/account/terms).

> As add-ons extend the computer version, they must be licensed under the AGPL3 or a compatible license. If you do not explicitly state a license, it will be assumed to be AGPL3.
