### ISSUE TITLE
Generate Mobile Cards error (FFmpeg not found?)

### ISSUE THREAD

**Issue by aleksejrs** [kelciour/movies2anki#7]
Debian GNU/Linux testing

Anki
Version 2.0.52
Qt 4.8.1 PyQt 4.9.1

FFmpeg is `/usr/bin/ffmpeg`

When I choose "`Generate Mobile Video Cards…`", the following message appears, with a "`Close`" button. When I press the `Close` button, a progress window appears with the name of the oldest video I have added, and "`0%`". There is no additional CPU load.

```
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "/home/fc/.local/share/Anki2/addons/movies2anki/player.py", line 464, in run
    self.fp = subprocess.Popen(cmd.encode(sys.getfilesystemencoding()), shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, startupinfo = info)
  File "subprocess.py", line 679, in __init__
  File "subprocess.py", line 1249, in _execute_child
OSError: [Errno 2] No such file or directory
```

**Comment by kelciour** [comment]
Yes, it looks like it coudn't find FFmpeg, but the strange thing is that it should have given you an warning when you tried to use "Generate Mobile Video Cards..." option (`Please install FFmpeg...`).

Does it happen again when you restart Anki? And after you restart Anki press Ctrl+Shift+; to open up [Debug Console](https://apps.ankiweb.net/docs/manual.html#debug-console), type the following commands and press Ctrl+Enter. What is the output? In your case it should be `/usr/bin/ffmpeg`.

	from distutils.spawn import find_executable
	print(find_executable("ffmpeg"))

**Comment by aleksejrs** [comment]
Yes, and the command works:

```
>>> from distutils.spawn import find_executable
... print(find_executable("ffmpeg"))
/usr/bin/ffmpeg
```

**Comment by kelciour** [comment]
Please use Anki - Tools - Add-ons - Open Add-ons Folder... and replace `player.py` in the movies2anki folder with the updated version downloaded from [this gist](https://gist.github.com/kelciour/6282f9aeab40f668ee5b1d95a2bb87f3). It should fix this issue.

**Comment by aleksejrs** [comment]
It seems to work, thanks.

**Comment by aleksejrs** [comment]
Now there is a one-time error when closing Anki after generating mobile cards. I'll post the output soon.

**Comment by aleksejrs** [comment]
When selecting `File → Switch Profile` in a session where I generated mobile cards:

```
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt/main.py", line 250, in unloadProfile
  File "anki/hooks.py", line 26, in runHook
  File "/home/fc/.local/share/Anki2/addons/movies2anki/player.py", line 595, in stopWorker
    mw.worker.cancel()
  File "/home/fc/.local/share/Anki2/addons/movies2anki/player.py", line 431, in cancel
    self.fp.terminate()
  File "subprocess.py", line 1462, in terminate
  File "subprocess.py", line 1457, in send_signal
OSError: [Errno 3] No such process
```

**Comment by kelciour** [comment]
Thanks! I've updated the [gist](https://gist.github.com/kelciour/6282f9aeab40f668ee5b1d95a2bb87f3) to fix it.

**Comment by aleksejrs** [comment]
It works.

**Comment by kelciour** [comment]
I'll close it as it's about Anki 2.0 and I created a new issue #28 to maybe fix the error message if File → Switch Profile was used while generating mobile cards.
