### ISSUE TITLE
Option to prohibit subtitle merging.

### ISSUE THREAD

**Issue by aleksejrs** [kelciour/movies2anki#9]
Pad Timings: 750.
Gap between Phrases: 0
[ ] Split Long Phrases
(*) Phrases

https://www.youtube.com/watch?v=Axsm6x3Cij8

```
1
00:00:10,260 --> 00:00:13,800
Wie viel Uhr ist es?

2
00:00:13,920 --> 00:00:17,380
Es ist ein Uhr.

3
00:00:17,380 --> 00:00:20,820
Es ist zwei Uhr.

4
00:00:21,000 --> 00:00:24,980
Es ist drei Uhr.
```
and so on.

The first two subtitles are merged into 
```
Wie viel Uhr ist es?
Es ist ein Uhr.
```

A few pairs of subtitles further in the file are also merged.

**Comment by kelciour** [comment]
Close movies2anki -> edit `config.ini` in the movies2anki add-on's folder (Tools - Add-ons - Open Add-ons Folder...) -> reopen movies2anki.

To disable it, change `join_questions_with_answers = True` to `join_questions_with_answers = False`.

**Comment by aleksejrs** [comment]
Thanks.
